### ISSUE TITLE
Calling `Conn.Close` gets stuck

### ISSUE THREAD

**Issue by besedad** [pion/dtls#390]
I have a basic dtls client and a listener sitting on the opposite side. Sometimes calling Close on client connection makes the program get stuck and the only remedy is to kill it. My suspicion is that there's some weird race condition at play somewhere down the line after calling Close.

With help of some prints placed around the code, I've tracked the problem down to this line[1] where things come full circle and I can't wrap my head around it. Hopefully someone else with more insight into the code can.

Here's how to reproduce the issue:

```golang
package main

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"fmt"
	"net"
	"time"

	"github.com/pion/dtls/v2"
	"github.com/pion/dtls/v2/pkg/crypto/selfsign"
	"github.com/pion/udp"
)

func main() {
	go func() {
		cert, err := selfsign.GenerateSelfSigned()
		if err != nil {
			panic(err)
		}

		listenAddress, err := net.ResolveUDPAddr("udp", fmt.Sprintf("%s:%d", "localhost", 8883))
		if err != nil {
			panic(err)
		}

		listener, err := dtls.Listen("udp", listenAddress, &dtls.Config{
			Certificates:         []tls.Certificate{cert},
			ExtendedMasterSecret: dtls.RequireExtendedMasterSecret,
			ConnectContextMaker: func() (context.Context, func()) {
				return context.WithTimeout(context.Background(), 30*time.Second)
			},
		})
		if err != nil {
			panic(err)
		}
		defer listener.Close()

		for {
			clientConn, err := listener.Accept()
			println("gw: connection accepted!")
			if err != nil {
				if _, ok := err.(*dtls.HandshakeError); ok {
					println("Client TLS handshake error")
					continue
				}
				if err == udp.ErrClosedListener {
					panic(err)
				}
				panic(fmt.Errorf("accept error: %v", err))
			}
			clientConn.Close()
		}
	}()

	// Client...
	for {
		cert, err := selfsign.GenerateSelfSigned()
		if err != nil {
			panic(err)
		}

		certPool, err := x509.SystemCertPool()
		if err != nil {
			panic(err)
		}

		hostAddress, err := net.ResolveUDPAddr("udp", "localhost:8883")
		if err != nil {
			panic(err)
		}

		// Prepare the configuration of the DTLS connection
		config := &dtls.Config{
			Certificates:         []tls.Certificate{cert},
			ServerName:           "localhost",
			InsecureSkipVerify:   true,
			ExtendedMasterSecret: dtls.RequireExtendedMasterSecret,
			RootCAs:              certPool,
		}

		// Connect to a DTLS server
		ctx2, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()
		println("cli: connecting")
		conn, err := dtls.DialWithContext(ctx2, "udp", hostAddress, config)
		if err != nil {
			panic(err)
		}

		println("cli: closing connection...")
		conn.Close()
		println("cli: closed!")
	}
}
```

[1] https://github.com/pion/dtls/blob/master/conn.go#L921

**Comment by jkralik** [comment]
I have a similar issue. This is a backtrace where stuck occurs:

```
2021-12-15T16:15:10.4042062Z goroutine 8287 [semacquire, 9 minutes]:
2021-12-15T16:15:10.4043642Z sync.runtime_SemacquireMutex(0x49f9f4, 0x88, 0xc000315750)
2021-12-15T16:15:10.4046002Z 	/usr/local/go/src/runtime/sema.go:71 +0x25
2021-12-15T16:15:10.4046719Z sync.(*Mutex).lockSlow(0xc00248e56c)
2021-12-15T16:15:10.4048276Z 	/usr/local/go/src/sync/mutex.go:138 +0x165
2021-12-15T16:15:10.4049676Z sync.(*Mutex).Lock(...)
2021-12-15T16:15:10.4051092Z 	/usr/local/go/src/sync/mutex.go:81
2021-12-15T16:15:10.4052961Z github.com/pion/transport/connctx.(*connCtx).Close.func1()
2021-12-15T16:15:10.4064152Z 	/go/pkg/mod/github.com/pion/transport@v0.12.3/connctx/connctx.go:153 +0x45
2021-12-15T16:15:10.4064790Z sync.(*Once).doSlow(0xc0005a0330, 0x500230)
2021-12-15T16:15:10.4065264Z 	/usr/local/go/src/sync/once.go:68 +0xd2
2021-12-15T16:15:10.4065663Z sync.(*Once).Do(...)
2021-12-15T16:15:10.4066064Z 	/usr/local/go/src/sync/once.go:59
2021-12-15T16:15:10.4066619Z github.com/pion/transport/connctx.(*connCtx).Close(0xc00248e540)
2021-12-15T16:15:10.4067326Z 	/go/pkg/mod/github.com/pion/transport@v0.12.3/connctx/connctx.go:152 +0x65
2021-12-15T16:15:10.4067970Z github.com/pion/dtls/v2.(*Conn).close(0xc0016dd200, 0x1)
2021-12-15T16:15:10.4068536Z 	/go/pkg/mod/github.com/pion/dtls/v2@v2.0.12/conn.go:915 +0x199
2021-12-15T16:15:10.4069100Z github.com/pion/dtls/v2.(*Conn).Close(0xc0016dd200)
2021-12-15T16:15:10.4069662Z 	/go/pkg/mod/github.com/pion/dtls/v2@v2.0.12/conn.go:335 +0x25
2021-12-15T16:15:10.4074200Z github.com/plgd-dev/go-coap/v2/net.(*Conn).Close(0x407438)
2021-12-15T16:15:10.4075133Z 	/go/pkg/mod/github.com/plgd-dev/go-coap/v2@v2.4.1-0.20211208140948-f07411c270b5/net/conn.go:57 +0x37
2021-12-15T16:15:10.4076033Z github.com/plgd-dev/go-coap/v2/dtls.(*Session).Close(0xc001924550)
2021-12-15T16:15:10.4076987Z 	/go/pkg/mod/github.com/plgd-dev/go-coap/v2@v2.4.1-0.20211208140948-f07411c270b5/dtls/session.go:85 +0x36
2021-12-15T16:15:10.4077898Z github.com/plgd-dev/go-coap/v2/udp/client.(*ClientConn).Close(...)
2021-12-15T16:15:10.4079139Z 	/go/pkg/mod/github.com/plgd-dev/go-coap/v2@v2.4.1-0.20211208140948-f07411c270b5/udp/client/clientconn.go:152
2021-12-15T16:15:10.4080121Z github.com/plgd-dev/go-coap/v2/udp/client.(*Client).Close(0xc0010d7290)
2021-12-15T16:15:10.4081102Z 	/go/pkg/mod/github.com/plgd-dev/go-coap/v2@v2.4.1-0.20211208140948-f07411c270b5/udp/client/client.go:64 +0x24
2021-12-15T16:15:10.4082006Z github.com/plgd-dev/device/pkg/net/coap.(*Client).Close(...)
2021-12-15T16:15:10.4082956Z 	/go/pkg/mod/github.com/plgd-dev/device@v0.0.0-20211207142208-da9ef1f51932/pkg/net/coap/client.go:312
2021-12-15T16:15:10.4083992Z github.com/plgd-dev/device/client/core.(*Device).Close(0xc000164ce8, {0x13e94a0, 0xc00132c690})
2021-12-15T16:15:10.4085040Z 	/go/pkg/mod/github.com/plgd-dev/device@v0.0.0-20211207142208-da9ef1f51932/client/core/device.go:84 +0x16a
2021-12-15T16:15:10.4086174Z github.com/plgd-dev/device/client.releaseOcfDevice({0x13e94a0, 0xc00132c690}, {0x1179280, 0xc0010d7290})
2021-12-15T16:15:10.4099373Z 	/go/pkg/mod/github.com/plgd-dev/device@v0.0.0-20211207142208-da9ef1f51932/client/refDevice.go:24 +0x45
2021-12-15T16:15:10.4101116Z github.com/plgd-dev/kit/v2/sync.(*RefCounter).Release(0xc00184d560, {0x13e94a0, 0xc00132c690})
2021-12-15T16:15:10.4102450Z 	/go/pkg/mod/github.com/plgd-dev/kit/v2@v2.0.0-20211006190727-057b33161b90/sync/refcounter.go:46 +0x53
2021-12-15T16:15:10.4103553Z github.com/plgd-dev/device/client.(*RefDevice).Release(...)
2021-12-15T16:15:10.4104834Z 	/go/pkg/mod/github.com/plgd-dev/device@v0.0.0-20211207142208-da9ef1f51932/client/refDevice.go:32
2021-12-15T16:15:10.4106200Z github.com/plgd-dev/device/client.(*refDeviceCache).Close(0xc00003d600, {0x13e94a0, 0xc00132c690})
2021-12-15T16:15:10.4107531Z 	/go/pkg/mod/github.com/plgd-dev/device@v0.0.0-20211207142208-da9ef1f51932/client/refDeviceCache.go:225 +0x155
2021-12-15T16:15:10.4108613Z github.com/plgd-dev/device/client.(*Client).Close(0xc00096c780, {0x13e94a0, 0xc00132c690})
2021-12-15T16:15:10.4109665Z 	/go/pkg/mod/github.com/plgd-dev/device@v0.0.0-20211207142208-da9ef1f51932/client/client.go:229 +0xae
2021-12-15T16:15:10.4110874Z github.com/plgd-dev/hub/test.OnboardDevSimForClient.func1()
2021-12-15T16:15:10.4111876Z 	/go/src/github.com/plgd-dev/hub/test/test.go:247 +0x25
2021-12-15T16:15:10.4113161Z github.com/plgd-dev/hub/test.OnboardDevSimForClient({0x13e94a0, 0xc00132c690}, 0xc0019c5d40, {0x140bad0, 0xc000c78b00}, {0x119b0b4, 0x4}, {0xc0013d25a0, 0x24}, {0x11a5ca3, ...}, ...)
2021-12-15T16:15:10.4114570Z 	/go/src/github.com/plgd-dev/hub/test/test.go:292 +0x8af
2021-12-15T16:15:10.4115375Z github.com/plgd-dev/hub/test.OnboardDevSim(...)
2021-12-15T16:15:10.4116150Z 	/go/src/github.com/plgd-dev/hub/test/test.go:304
2021-12-15T16:15:10.4117263Z github.com/plgd-dev/hub/grpc-gateway/service_test.TestRequestHandlerGetDevices(0x0)
2021-12-15T16:15:10.4118534Z 	/go/src/github.com/plgd-dev/hub/grpc-gateway/service/getDevices_test.go:73 +0x6cd
2021-12-15T16:15:10.4119243Z testing.tRunner(0xc0019c5d40, 0x11efff0)
2021-12-15T16:15:10.4119817Z 	/usr/local/go/src/testing/testing.go:1259 +0x102
2021-12-15T16:15:10.4120287Z created by testing.(*T).Run
2021-12-15T16:15:10.4120784Z 	/usr/local/go/src/testing/testing.go:1306 +0x35a

2021-12-15T16:15:10.6694665Z goroutine 9074 [semacquire, 9 minutes]:
2021-12-15T16:15:10.6695195Z sync.runtime_Semacquire(0xc0006f3e20)
2021-12-15T16:15:10.6695722Z 	/usr/local/go/src/runtime/sema.go:56 +0x25
2021-12-15T16:15:10.6696198Z sync.(*WaitGroup).Wait(0xc000d2fc80)
2021-12-15T16:15:10.6696713Z 	/usr/local/go/src/sync/waitgroup.go:130 +0x71
2021-12-15T16:15:10.6697460Z github.com/pion/transport/connctx.(*connCtx).WriteContext(0xc00248e540, {0x13e93f8, 0xc00248e5c0}, {0xc0006f3e20, 0x1f, 0x20})
2021-12-15T16:15:10.6698316Z 	/go/pkg/mod/github.com/pion/transport@v0.12.3/connctx/connctx.go:140 +0x250
2021-12-15T16:15:10.6699263Z github.com/pion/dtls/v2.(*Conn).writePackets(0xc0016dd200, {0x13e93f8, 0xc00248e5c0}, {0xc0012c3d60, 0x1, 0x13e93f8})
2021-12-15T16:15:10.6699983Z 	/go/pkg/mod/github.com/pion/dtls/v2@v2.0.12/conn.go:397 +0x7f1
2021-12-15T16:15:10.6700650Z github.com/pion/dtls/v2.(*Conn).notify(0xc0016dd200, {0x13e93f8, 0xc00248e5c0}, 0x1, 0x0)
2021-12-15T16:15:10.6701338Z 	/go/pkg/mod/github.com/pion/dtls/v2@v2.0.12/conn.go:757 +0x1ea
2021-12-15T16:15:10.6702015Z github.com/pion/dtls/v2.(*Conn).readAndBuffer(0xc0016dd200, {0x13e93f8, 0xc00248e5c0})
2021-12-15T16:15:10.6702701Z 	/go/pkg/mod/github.com/pion/dtls/v2@v2.0.12/conn.go:567 +0x35c
2021-12-15T16:15:10.6703305Z github.com/pion/dtls/v2.(*Conn).handshake.func3()
2021-12-15T16:15:10.6703917Z 	/go/pkg/mod/github.com/pion/dtls/v2@v2.0.12/conn.go:826 +0xfa
2021-12-15T16:15:10.6704561Z created by github.com/pion/dtls/v2.(*Conn).handshake
2021-12-15T16:15:10.6705172Z 	/go/pkg/mod/github.com/pion/dtls/v2@v2.0.12/conn.go:815 +0x3e5
```
