### ISSUE TITLE
OpenSSL E2E Tests are broken in Go 1.20

### ISSUE THREAD

**Issue by stv0g** [pion/dtls#526]
PR is #525 

Failing tests: https://github.com/pion/dtls/actions/runs/4092274657/jobs/7056887569

Alle the OpenSSL tests are failing in the Goroutine check:

```
  util.go:41: Unexpected routines on test startup: 
        goroutine 1098 [chan send, 2 minutes]:
        os/exec.(*Cmd).watchCtx(0xc0002e4160, 0xc00006a1e0)
        	/usr/local/go/src/os/exec/exec.go:782 +0x413
        created by os/exec.(*Cmd).Start
        	/usr/local/go/src/os/exec/exec.go:743 +0x9f3
        
        goroutine 1067 [chan send, 2 minutes]:
        os/exec.(*Cmd).watchCtx(0xc0002e4000, 0xc000083140)
        	/usr/local/go/src/os/exec/exec.go:782 +0x413
        created by os/exec.(*Cmd).Start
        	/usr/local/go/src/os/exec/exec.go:743 +0x9f3
        
        goroutine 1114 [chan send, 2 minutes]:
        os/exec.(*Cmd).watchCtx(0xc00010c000, 0xc00024bc20)
        	/usr/local/go/src/os/exec/exec.go:782 +0x413
        created by os/exec.(*Cmd).Start
        	/usr/local/go/src/os/exec/exec.go:743 +0x9f3
```

I don't really know why this is happening.. Maybe @jkralik or @daenney have an idea?

**Comment by hasheddan** [comment]
Looks like this additional goroutine was introduced by https://github.com/golang/go/commit/55eaae452cf69df768b2aaf6045db22d6c1a4029, which was included starting in Go 1.20. I'll assign myself and open a fix here 👍🏻
